### ISSUE TITLE
Getting "read less than dataLength" Exception while trying to access "EnumHub" function.

### ISSUE THREAD

**Issue by orozcodiaz** [fawno/SoftEtherApi-PHP#15]
Calling `HubApi->GetList()` throws an error `read less than dataLength`.
Also started to get "Peer certificate verification failure" when trying to connect via OpenVPN.

**Comment by alphp** [comment]
With my SoftEther server the following code works correctly:
```php
  $softEther = new SoftEther('vpn.example.com', 443);
  $res = $softEther->Connect();
  $authRes = $softEther->Authenticate($password);
  $hubs = $softEther->HubApi->GetList();
```
Could you put the exception dump?
Could you detail your code a little?
Do you attack a server in production or testing?

**Comment by hazg** [comment]
```php
$softEther = new SoftEtherApi\SoftEther('se', 443);
$res = $softEther->Connect();
$authRes = $softEther->Authenticate('123', );
$hubs = $softEther->HubApi->GetList();
```

```
Fatal error: Uncaught Exception: read less than dataLength in /var/www/html/vendor/fawno/softether-api/src/SoftEther.php:131
Stack trace:
#0 /var/www/html/vendor/fawno/softether-api/src/Api/SoftEtherHub.php(123): SoftEtherApi\SoftEther->CallMethod('EnumHub')
#1 /var/www/html/api/protocols/sstp/test.php(16): SoftEtherApi\Api\SoftEtherHub->GetList()
#2 {main}
  thrown in /var/www/html/vendor/fawno/softether-api/src/SoftEther.php on line 131
```

dockerized server: softethervpn/vpnserver:v4.42-9798-rtm (stable - too)
PHP 8.1.31
